name: Check Commits

on:
  workflow_call:

permissions:
  contents: read
  deployments: write
  issues: write
  pull-requests: write

jobs:
  check-commits:
    name: Check Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/check-commits
        with:
          os: ubuntu-latest
          node-version: 22
          github-token: ${{ secrets.GITHUB_TOKEN }}
