on:
  workflow_call:

permissions:
  contents: write
  deployments: write
  issues: write
  pull-requests: write

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Run auro rc-workflow
        run: npx --ignore-scripts --package=@aurodesignsystem/auro-cli -- auro rc-workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}